### PR TITLE
improve geometry and add attributes to Zalew Wocławski

### LINKED ISSUE #486: Zalew Włocławski - river shapefile and lake shapefile misaligned
This issue concerns mismatch between datasets concerning single waterbody - https://www.openstreetmap.org/relation/2329477/history#map=11/52.5968/19.4362

in 10m datasets rivers is outside its own reservoir what makes no sense

screen01

I would be happy to try contribute a fix, using Geoportal.gov.pl imagery available without limits on its use.

Should I open https://github.com/nvkelso/natural-earth-vector/tree/master/10m_physical in QGIS, save it and submit PR?

(BTW, contributing.md file where info about how typical contribution proceeds seems missing)

### PR DESCRIPTION
**Pull request by matkoniecz**
geometry is now both accurate and has lower number of points to express a shape

both lake and river geometry was fixed

based on geoportal.gov.pl imagery (available without restrictions) and names taken from memory and Wikipedia + wikidata id from Wikipedia

fixes #486

--------------------------------------------------

Is there some reasonable method of improving geometry accuracy in QGIS? "click node, click its location" is quite frustrating after editing in JOSM with its great editing mode for geometry tweaking.

### CODE REVIEW

**Comment by nvkelso** [comment]
Ah, the reason the Lake wasn't aligned is it's the Europe supplemental and it didn't have the consistent quality checks applied when it was added later.

Can you attach screenshots before/after like you did with the other PR, please?

**Comment by matkoniecz** [comment]
screen02

**Comment by matkoniecz** [comment]
BTW, looking at data in general - it seems that supplemental lakes dataset at least in Poland is generally moved toward North by some vector (seems about 800m, have not measured it).

Probably it is not my mistake as it is moved by similar/the same offset from NE global waterway centerlines.

**Comment by matkoniecz** [comment]
screen04

Łebsko Lake as a random example

**Comment by nvkelso** [comment]
Oh my, I see what you mean – I see the ~800 meter offset all over Europe. Generally it seems like all the features in the layer _should_ move south that amount... but then what about the supplemental Europe rivers? It seems like they should move south too... but some care was taken before to connect those to the basic river network. So this could turn out to be a significant chunk of work. Let me ponder it a bit...

**Comment by matkoniecz** [comment]
Maybe move them country by country? So it is not some outrageous amount of work in one go?

Maybe open issues for every country and slowly process that?

**Comment by nvkelso** [comment]
Let's see how much @elliotap and @MrGawsome can get done for v5.1 in a sprint to move them all around. Whatever is left let's peel off as separate per country issues as you suggest.

**Comment by nvkelso** [comment]
For simplicity's sake, I'm going to close this PR but we will reference your changes here in a larger upcoming PR.

**Pull request closed without merging**
