### PR TITLE
[WIP] Add USA admin-2 counties

### LINKED ISSUE #175: Add USA adm2 county polygons
Initially 10m scaleset only, 50m maybe later.

### PR DESCRIPTION
**Pull request by nvkelso**
Fixes #175.

### CODE REVIEW

**Comment by nvkelso** [comment]
@ImreSamu if you're so inclined, this PR and the other recently merged PR https://github.com/nvkelso/natural-earth-vector/pull/534 for ports and geo label polys add `ne_id` but are also missing `wikidataid` which powers all the name localization if you are available to add it :)

Aside: I need to dust off the wikidata name localization script and get it working again, too. Some things changed with the `ne_id` tools script (eg https and a little Python modernization).

**Comment by ImreSamu** [comment]
>  also missing wikidataid

@nvkelso : OK ...  I have added to my to-do list :
* expected  ~ in the coming weeks / days

**Comment by nvkelso** [comment]
I am rebuilding the `admin-2-county` polygons to build using same Mapshaper process we use to maintain `admin-1-states-provinces`. I used Mapshaper to identify the topological boundaries between the polygons and save them as lines, plus inner centroid for label points details, and exploided multi-part to single-part inner centroids for the basic label points. I went thru the lines that overlapped with ocean coastline, country boundaries, and state boundaries and culled them with select by location (using a buffer) and manual review. Mapshaper's output was sometimes funky (a tolerance issue &/or minor funk with the input polygons?) so I had to resolve ~100 overlapping and confusing lines, and then the coastline between the datasets was slightly different in all the barrier islands. The other thing I'm working thru is the great lakes counties stopped at the shoreline, but our practice in Natural Earth is to continue them out into the lake and offer two versions (with and without lakes). 

I used this [low rez EPA source](https://www.epa.gov/greatlakes/facts-and-figures-about-great-lakes) to rough that in, but it could use some more eyeballs.

image

Versus my working file:

image

There are still some issues, as you can see with the Mapshaper output (below). The biggest is we should have **3,225** features but only have 3,213 (12 off). But by the time we get the final output there are 41 and 11 bad spatial and data joins to debug.

```$ make build_a8_ne_10m_admin_2_all
mapshaper -i combine-files snap \
		10m_cultural/ne_10m_admin_0_boundary_lines_land.shp \
		10m_cultural/ne_10m_admin_0_boundary_lines_map_units.shp \
		10m_physical/ne_10m_coastline.shp \
		10m_physical/ne_10m_minor_islands_coastline.shp \
		10m_cultural/ne_10m_admin_1_states_provinces_lines.shp \
		10m_cultural/ne_10m_admin_2_counties_lines.shp \
		-filter-fields \
		-merge-layers \
		-polygons gap-tolerance=1e-4 \
		-join 10m_cultural/ne_10m_admin_2_label_points.shp \
		-filter 'ADM0_SR !== null' + \
		-o 10m_cultural/ne_10m_admin_2_counties_scale_rank_minor_islands.shp \
		-filter 'ADM0_SR <= 6' + \
		-o 10m_cultural/ne_10m_admin_2_counties_scale_rank.shp \
		-dissolve 'ADM2_CODE' copy-fields=FEATURECLA,SCALERANK \
		-join 10m_cultural/ne_10m_admin_2_label_points_details.dbf encoding=utf8 keys=ADM2_CODE,ADM2_CODE fields=* \
		-o 10m_cultural/ne_10m_admin_2_counties.shp \
		-erase intermediate/ne_10m_lakes_big.shp \
		-o 10m_cultural/ne_10m_admin_2_counties_lakes.shp \
#  calc='join_count = count()'
[i] Snapped 5037 points
[join] Joined data from 3,655 source records to 3,584 target records
[join] 10930/14514 target records received no data
[join] 1/3656 source records could not be joined
[join] 41/14514 target records were matched by multiple source records (many-to-one relationship)
[join] Inconsistent values were found in fields [ADM2_CODE,NAME] during many-to-one join. Values in the first joining record were used.
[filter] Retained 3,584 of 14,514 features
[o] Wrote 10m_cultural/ne_10m_admin_2_counties_scale_rank_minor_islands.shp
[o] Wrote 10m_cultural/ne_10m_admin_2_counties_scale_rank_minor_islands.shx
[o] Wrote 10m_cultural/ne_10m_admin_2_counties_scale_rank_minor_islands.dbf
[o] Wrote 10m_cultural/ne_10m_admin_2_counties_scale_rank_minor_islands.prj
[filter] Retained 3,584 of 3,584 features
[o] Wrote 10m_cultural/ne_10m_admin_2_counties_scale_rank.shp
[o] Wrote 10m_cultural/ne_10m_admin_2_counties_scale_rank.shx
[o] Wrote 10m_cultural/ne_10m_admin_2_counties_scale_rank.dbf
[o] Wrote 10m_cultural/ne_10m_admin_2_counties_scale_rank.prj
[dissolve] Dissolved 3,584 features into 3,213 features
[join] Joined data from 3,214 source records to 3,213 target records
[join] 11/3225 source records could not be joined
[join] 1/3213 target records were matched by multiple source records (many-to-one relationship)
[join] Inconsistent values were found in fields [AREA_SQKM,NE_ID] during many-to-one join. Values in the first joining record were used.
[o] Wrote 10m_cultural/ne_10m_admin_2_counties.shp
[o] Wrote 10m_cultural/ne_10m_admin_2_counties.shx
[o] Wrote 10m_cultural/ne_10m_admin_2_counties.dbf
[o] Wrote 10m_cultural/ne_10m_admin_2_counties.prj
[o] Wrote 10m_cultural/ne_10m_admin_2_counties_lakes.shp
[o] Wrote 10m_cultural/ne_10m_admin_2_counties_lakes.shx
[o] Wrote 10m_cultural/ne_10m_admin_2_counties_lakes.dbf
[o] Wrote 10m_cultural/ne_10m_admin_2_counties_lakes.prj
```

**Comment by nvkelso** [comment]
@ImreSamu when you get to the **wikidataid** work, please use either:

- **ne_10m_admin_2_label_points_details** in this branch (which has the correct number of features, with the latitude and longitude marked in DBF and in SHP)

Or an earlier version of the counties polygon SHP that doesn't have the problem of missing features:

- https://github.com/nvkelso/natural-earth-vector/blob/3ca5556023d9866269d2f81201b7d36936f10a93/10m_cultural/ne_10m_admin_2_counties.dbf
- https://github.com/nvkelso/natural-earth-vector/blob/3ca5556023d9866269d2f81201b7d36936f10a93/10m_cultural/ne_10m_admin_2_counties.shp
- https://github.com/nvkelso/natural-earth-vector/blob/3ca5556023d9866269d2f81201b7d36936f10a93/10m_cultural/ne_10m_admin_2_counties.shx

**Comment by nvkelso** [comment]
We should have `3,143` US counties in the 50 states plus DC, and then another `78` in Puerto Rico = 3,221 total expected in this theme.

It turns out there were duplicate Fairfax county, Virginia features in the original count of `3,225` in this draft PR, which brings it down to 3224. Which is still 3 extra 🤔

**Comment by nvkelso** [comment]
I reviewed the last decades worth of county & county equivalent changes and there's 2 Alaska county equivalents that need resolution. Alaskan boroughs of Chugach and Copper River, both established in 2019 were formed by dividing Valdez–Cordova Census Area in 1/2 and removing the former equivalent completely (no remainder).

```
FIPS: 02063
Chugach
Chugach Census Area
ne_id: 1730108941

FIPS: 02066
Copper River
Copper River Census Area
ne_id: 1730108939
```

image
From [Wikipedia](https://en.wikipedia.org/wiki/List_of_boroughs_and_census_areas_in_Alaska)

What's in this draft PR before:
image

And now after, traced from Census 2020 Tiger linework:
image

**Comment by nvkelso** [comment]
Comparing the counts of counties between US Census 2019 file and this draft PR, I see the expected delta of +1 in Alaska, and a mystery +1 in Virginia. Looking closer that's because per Wikipedia:

> Bedford, VA was designated as an independent city in 1968, but remained the county seat of Bedford County, VA. Its status as an independent city was ended on July 1, 2013, returning to a town within Bedford County.

Which matches what's in the US Census SHP, so I'll delete that feature and we're at 100% match.

**Comment by nvkelso** [comment]
My local changes look good... but along the way I started modifying the admin-0 and admin-1 lines in the USA which suddenly implicates my other disputed territory worldview / point-of-view (POV) branch. I'll sort that out next.

**Comment by ImreSamu** [comment]
First proposal:


### my method:

* merged a wikidataid proposal based on FIPS ( ~ "Left Join")
  * 4 FIPS has no match 
* validated my script.
  * added sugestion for the 4 FIPS ( "light red" color)
  * detected utf8 problem in the name ( "yellow" color )

* based on:
  * this week wikidata JSON dump ( ~ latest )
  * `origin/nvkelso/175-usa-counties` : 2021May20


### Results: Google Sheets links:

https://docs.google.com/spreadsheets/d/14jwD6StQ_vsKlCNuRj7G5-rfxA21KkK2qM6W4kpUoSw/edit?usp=sharing
  
  * "ne_wd_id" = COALESCE(current wikidataid, Left Joined wikidataid proposals by fips)
     * so this is not the current source content!
  *  "_suggested_wd_id" = contains the +4 suggestions ( with "light red") 

#### FIPS differences - compare to Wikidata ( "light red" in the sheets )

maybe related to this - but need a manual check:
* https://www.census.gov/programs-surveys/geography/technical-documentation/county-changes.2010.html



```sql
+-----------+---------+---------------------------+---------+------------+---------------+
|   wd_id   | wd_fips |        wd_name_en         | ne_fips |   ne_id    |    ne_name    |
+-----------+---------+---------------------------+---------+------------+---------------+
|           |         |                           | 02232   | 1730096909 | Hoonah-Angoon |
|           |         |                           | 02270   | 1730096407 | Wade Hampton  |
|           |         |                           | 02280   | 1730096915 | Petersburg    |
|           |         |                           | 46113   | 1730094721 | Shannon       |
| Q500827   | 02105   | Hoonah–Angoon Census Area |         |            |               |
| Q379474   | 02158   | Kusilvak Census Area      |         |            |               |
| Q25408755 | 02195   | Petersburg Borough        |         |            |               |
| Q495201   | 46102   | Oglala Lakota County      |         |            |               |
+-----------+---------+---------------------------+---------+------------+---------------+
(8 rows)

wd_fips = P882 - FIPS 6-4 (US counties) ( https://www.wikidata.org/wiki/Property:P882 )
ne_fips = substr(fips,3,5)  ( `10m_cultural/ne_10m_admin_2_label_points_details` )
   commit 5a34ac8818983423a0c449cc7e43ffbb5368224d (HEAD, origin/nvkelso/175-usa-counties)
   Date:   Thu May 20 02:30:26 2021 -0700
```


### UTF8 problem?  ( "yellow" in the sheets )

IMHO: need re-check; in my system some characters missing. 

ne_id      | ne_name    | new_wd_label    | _suggested_wd_id
-----------| -----------| ----------------| -----------------
1730093435 | Doa Ana    | Doña Ana County | Q112953
1730096241 | Aasco      | Añasco          | Q2390910
1730096265 | Catao      | Cataño          | Q768483
1730096285 | Gunica     | Guánica         | Q1019645
1730096317 | Loza       | Loíza           | Q1853983
1730096321 | Manat      | Manatí          | Q674599
1730096341 | Peuelas    | Peñuelas        | Q369880
1730096349 | Rincn      | Rincón          | Q1815896
1730096351 | Ro Grande  | Río Grande      | Q979996


### extreme distance check - looks OK

"Aleutians West Census Area" Q185533  **700-800km**
* IMHO: big area; so looks OK
   * https://www.openstreetmap.org/relation/2605254#map=2/42.7/162.8

### Other FIPS in Wikidata AND no NE match:


IMHO:
in any case, it will be easy to merge by "fips -> wikidataid"


```sql
+-----------+---------+-------------------------------+---------+-------+---------+
|   wd_id   | wd_fips |          wd_name_en           | ne_fips | ne_id | ne_name |
+-----------+---------+-------------------------------+---------+-------+---------+
| Q2625563  | 60010   | Eastern District              |         |       |         |
| Q1247537  | 60020   | Manu'a District               |         |       |         |
| Q1636779  | 60030   | Rose Atoll                    |         |       |         |
| Q1128488  | 60040   | Swains Island                 |         |       |         |
| Q2437227  | 60050   | Western District              |         |       |         |
| Q221684   | 64002   | Chuuk State                   |         |       |         |
| Q1785093  | 64005   | Kosrae State                  |         |       |         |
| Q7771127  | 64040   | Pohnpei State                 |         |       |         |
| Q11342951 | 64060   | Yap State                     |         |       |         |
| Q16635    | 66010   | Guam                          |         |       |         |
| Q405164   | 68007   | Ailinginae Atoll              |         |       |         |
| Q405165   | 68010   | Ailinglaplap Atoll            |         |       |         |
| Q405378   | 68030   | Ailuk Atoll                   |         |       |         |
| Q694057   | 68040   | Arno Atoll                    |         |       |         |
| Q260549   | 68050   | Aur Atoll                     |         |       |         |
| Q697812   | 68060   | Bikar Atoll                   |         |       |         |
| Q152225   | 68070   | Bikini Atoll                  |         |       |         |
| Q700138   | 68073   | Bokak Atoll                   |         |       |         |
| Q152754   | 68080   | Ebon Atoll                    |         |       |         |
| Q649190   | 68090   | Enewetak Atoll                |         |       |         |
| Q703618   | 68100   | Erikub Atoll                  |         |       |         |
| Q697805   | 68110   | Jabat Island                  |         |       |         |
| Q168576   | 68120   | Jaluit Atoll                  |         |       |         |
| Q715830   | 68130   | Jemo Island                   |         |       |         |
| Q697832   | 68140   | Kili Island                   |         |       |         |
| Q309172   | 68150   | Kwajalein                     |         |       |         |
| Q741121   | 68160   | Lae Atoll                     |         |       |         |
| Q376862   | 68170   | Lib Island                    |         |       |         |
| Q518353   | 68180   | Likiep Atoll                  |         |       |         |
| Q12919    | 68190   | Majuro                        |         |       |         |
| Q567926   | 68300   | Maloelap Atoll                |         |       |         |
| Q703543   | 68310   | Mejit Island                  |         |       |         |
| Q700051   | 68320   | Mili Atoll                    |         |       |         |
| Q697819   | 68330   | Namdrik Atoll                 |         |       |         |
| Q703627   | 68340   | Namu Atoll                    |         |       |         |
| Q542619   | 68350   | Rongelap Atoll                |         |       |         |
| Q697826   | 68360   | Rongerik Atoll                |         |       |         |
| Q703587   | 68385   | Toke Atoll                    |         |       |         |
| Q697802   | 68390   | Ujae Atoll                    |         |       |         |
| Q703596   | 68400   | Ujelang Atoll                 |         |       |         |
| Q700015   | 68410   | Utirik Atoll                  |         |       |         |
| Q175931   | 68420   | Wotho Atoll                   |         |       |         |
| Q518210   | 68430   | Wotje Atoll                   |         |       |         |
| Q1608103  | 69085   | Northern Islands Municipality |         |       |         |
| Q949090   | 69100   | Rota                          |         |       |         |
| Q51679    | 69110   | Saipan                        |         |       |         |
| Q7808227  | 69120   | Tinian Municipality           |         |       |         |
| Q405589   | 70002   | Aimeliik                      |         |       |         |
| Q407967   | 70004   | Airai                         |         |       |         |
| Q530813   | 70010   | Angaur                        |         |       |         |
| Q3516752  | 70050   | Hatohobei                     |         |       |         |
| Q871222   | 70100   | Kayangel                      |         |       |         |
| Q189426   | 70150   | Koror                         |         |       |         |
| Q12898552 | 70212   | Melekeok                      |         |       |         |
| Q1154127  | 70214   | Ngaraard                      |         |       |         |
| Q1070185  | 70218   | Ngarchelong                   |         |       |         |
| Q1144496  | 70222   | Ngardmau                      |         |       |         |
| Q430385   | 70224   | Ngatpang                      |         |       |         |
| Q1070180  | 70226   | Ngchesar                      |         |       |         |
| Q975076   | 70227   | Ngeremlengui                  |         |       |         |
| Q1154101  | 70228   | Ngiwal                        |         |       |         |
| Q497981   | 70350   | Peleliu                       |         |       |         |
| Q866699   | 70370   | Sonsorol                      |         |       |         |
| Q46879    | 74050   | Baker Island                  |         |       |         |
| Q131305   | 74100   | Howland Island                |         |       |         |
| Q62218    | 74150   | Jarvis Island                 |         |       |         |
| Q131008   | 74200   | Johnston Atoll                |         |       |         |
| Q130895   | 74250   | Kingman Reef                  |         |       |         |
| Q47863    | 74300   | Midway Atoll                  |         |       |         |
| Q25359    | 74350   | Navassa Island                |         |       |         |
| Q123076   | 74400   | Palmyra Atoll                 |         |       |         |
| Q43296    | 74450   | Wake Island                   |         |       |         |
+-----------+---------+-------------------------------+---------+-------+---------+
(72 rows)

```

**Comment by nvkelso** [comment]
@ImreSamu Your suggestions look great, thank you! 

I agree with all your WikidataID suggestions. Thanks for flagging the old FIPS codes & name changes, and the bad character encoding issue in Puerto Rico. For other projects I recall previously US Census uses a different character encoding than one would expect and getting bit by that, so not surprising to see it again here 🤷 

I've applied your suggestions over in https://github.com/nvkelso/natural-earth-vector/pull/538, which is a redux of this PR that builds on a different branch to accomodate some breaking changes over there.

**Comment by nvkelso** [comment]
Continued in https://github.com/nvkelso/natural-earth-vector/pull/538, which has been merged. Thanks everyone!

**Pull request closed without merging**
