### PR TITLE
PR#507 Fixes and Unified Deep Water System of European Russia Fixes for Issues #500, #340, and #14

### PR DESCRIPTION
**Pull request by MrGawsome**
This PR includes work I did in my previous 2 PR’s, #502 and #507. For this new PR though, I made edits to fix the issues of PR#507 and I made edits dealing with the Unified Deep Water System, which derive from issues #500, #340, and #14. See below for a summary of these edits:

**PR#507 cleanup:**

After resolving the PR conflict, I:

For #236, I re-edited ne_id = 1159104649 in the ne_10m_geography_regions_polys shapefile. I added Wikidata “Q252609, ”changed the name and name_alt fields to “New Swabia” and “Neuschwabenland” respectively, and added “New Swabia” as the label.

Deleted spurious feature with no geometry in the ne_10m_rivers_lake_centerlines.dbf.

Edited the Lop Nur playa in both the ne_10m_playas and ne_50m_playas shapefiles to include the Lop Nur historic lake shape from the ne_10m_lakes_historic shapefile. For the 50m, I made the shape a little more generic to not copy the shape from the 10m.

Edited the ne_50m_lakes shapefile to thicken parts of the North Aral Sea and make parts less spikey.

Snapped the Amu and Syr Dayra rivers to the borders of the South Aral Sea and North Aral Sea. After investigating the eastern spur of the Amu Darya river, it was unclear where the headwaters of the river came from. It seems that there is multiple sources feeding into different parts along this river, so I left the river as is to avoid confusion. Let me know if you want me to connect the river to the playa instead.

I copied all river edits from the ne_10m_rivers_lake_centerlines file and applied them to the ne_10m_rivers_lake_centerlines_scale_rank. I did this for both 10m and 50m when applicable.

**Unified Deep Water System of European Russia Edits:**

1. I moved some rivers and lake centerlines that are part of the Unified Deep Water System of European Russia from the ne_10m_rivers_europe shapefile to the ne_10m_rivers_lake_centerlines shapefile. For some of these rivers, I added names, rivernum, wikidata, etc. and adjusted some of the geometries to make the data a little cleaner following imagery and to have connections between rivers and lake centerlines. Also, this way we can have proper dissolve fields for both 10m and 50m (50m dissolve field relies on names, not rivernum!).

2. I changed the zoom level of various rivers and lake centerlines. See the below graphic for more details. Note, the Volga river already had z3 applied to it, so no changes there.

image

3. I added canals and some small river segments to connect rivers properly between rivers and lake centerlines. I added ne_id’s and other attributes to these rivers based upon surrounding features, river importance, and research. In some scenarios, I changed a few attributes of the adjacent river to be consistent and to stress that these waterways are part of this water system (such as with the Moskva River). Below are new canals and rivers I added either from scratch or I added names (+other attributes) to:
Volga-Don Canal at 48.61678139, 44.07983692
Moscow Canal at 56.10971870, 37.62358107
Kovzha River at 60.62449713, 37.13591139
Moskva River at 55.76313584, 37.51009819

Research to support Kovzha River and Moskva River name additions:
Kovzha River:
Russian State Water Registry: http://textual.ru/gvr/index.php?card=175427
Great Soviet Encyclopedia: http://bse.sci-lib.com/article062337.html
Wiki: https://en.wikipedia.org/wiki/Kovzha
Wikidata: https://www.wikidata.org/wiki/Q2305285
OSM: https://www.openstreetmap.org/relation/9909117

Moskva River:
Russian State Water Registry: http://textual.ru/gvr/index.php?card=178461
Great Soviet Encyclopedia: http://bse.sci-lib.com/article078402.html
Wiki: https://en.wikipedia.org/wiki/Moskva_(river)
Wikidata: https://www.wikidata.org/wiki/Q175117
OSM: https://www.openstreetmap.org/relation/389341

### CODE REVIEW

**Comment by MrGawsome** [comment]
@nvkelso I made a new PR to include my Russian water system edits as well as the fixes you wanted for the previous PR#507. Let me know if you have any questions or need any other edits and I'd be more than happy to help!

**Comment by nvkelso** [comment]
> Also, this way we can have proper dissolve fields for both 10m and 50m (50m dissolve field relies on names, not rivernum!).

Oh my, that's a good catch and weird!

**Comment by nvkelso** [comment]
> For #236, I re-edited ne_id = 1159104649 in the ne_10m_geography_regions_polys shapefile. I added Wikidata “Q252609, ”changed the name and name_alt fields to “New Swabia” and “Neuschwabenland” respectively, and added “New Swabia” as the label.

This change looks good, thanks for fixing the conflict and replaying the edit.

But it's odd that I see **ne_id** = `1159104649` on 200 features? Looking back to released v4.1 I see the same problem – so I'll file a separate followup issue to untangle that :\

**Comment by nvkelso** [comment]
> Snapped the Amu and Syr Dayra rivers to the borders of the South Aral Sea and North Aral Sea. After investigating the eastern spur of the Amu Darya river, it was unclear where the headwaters of the river came from. It seems that there is multiple sources feeding into different parts along this river, so I left the river as is to avoid confusion. Let me know if you want me to connect the river to the playa instead.

Sounds like if anything it'd be a "dotted line" trailing off into the sands so agree no-op is the way forward. Thanks for checking!

**Comment by nvkelso** [comment]
For the Moscow Canal we have a pickle. The Europe supplement is meant to be optional, but the canal partially follows the channel of the Klyazma river. So the gap is resolved, I'll extend the northern section of the canal south to the south portion of the canal, exactly along the Europe supplemental geometry. The two features have the same stroke weight already.

image

image

**Comment by nvkelso** [comment]
From https://github.com/nvkelso/natural-earth-vector/issues/500#issuecomment-806259133 per @Maxszik:

> A part of the Unified Deep Water System of European Russia is the Belaya River, a tributary of the Kama, from the Kama to Ufa.

I also changed the **min_zoom** = `6.0` and **min_label** = `7.0` to match what we did for Moscow Canal situation.

**Comment by nvkelso** [comment]
Thanks @MrGawsome! Super awesome to see this work merged :)

**Pull request merged**
