### PR TITLE
Added missing ISO 3166-2 codes and fixed some incorrect ones

### PR DESCRIPTION
**Pull request by xelrach**
This changes adds some missing ISO 3166-2 codes and fixes some incorrect ones in 10m_cultural/ne_10m_admin_1_states_provinces.dbf . In addition, the ISO 3166-2 codes have been copied to 10m_cultural/ne_10m_admin_1_states_provinces_lakes.dbf .

### CODE REVIEW

**Comment by nvkelso** [comment]
Thanks @xelrach! I'm at the NACIS annual meeting (#nacis2015 on Twitter) so it might be until next week until I have a chance to look at this closely.

**Comment by xelrach** [comment]
Hey @nvkelso , just wanted to ping you to remind you about this.

**Comment by nvkelso** [comment]
This needs to also be fixed in the [points](https://github.com/nvkelso/natural-earth-vector/blob/master/10m_cultural/ne_10m_admin_1_label_points.dbf) source file, as all other files are derived from it during the build.

**Comment by xelrach** [comment]
Updated the points details file.

**Comment by nvkelso** [comment]
Thanks, this is a huge help! I've incorporated your changes into PR #199 and aa6d286dccec17a4cef552ca49ae6a1899887745 specifically. Closing this PR in favor of that one.

**Pull request closed without merging**
