### PR TITLE
Mazury lakes - improve geometry quality

### LINKED ISSUE #488: Wielkie Jeziora Mazurskie - 10m has poor tracing
Obviously, at 10m scale full details should not be expected.

But it seems to me that https://www.openstreetmap.org/#map=10/53.8857/21.5195 tracing can be improved to better match actual geometry and to provide better topology

Background: basically real data

Red outline: 10m_lakes dataset

screen02

### PR DESCRIPTION
**Pull request by matkoniecz**
fixes #488

I worry a bit that I made them too detailed, but if I counted correctly node count is now reduced, match to actual geometry and topology (as experienced during sailing) much better

red old, green new
screen10

### CODE REVIEW

**Comment by matkoniecz** [comment]
Checks fails due to unrelated

```
toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit

The command "docker build -t ne_py3wikidata ." failed and exited with 1 during .

Your build has been stopped.
```

**Comment by nvkelso** [comment]
The geometry detail looks OK to me. Can you also add the `10m_rivers_lake_centerlines` theme and make sure you the lines are consistent, and update your screenshot, please? The rivers should still come in and out of the lakes on a node... and the lake centerlines need to be 100% inside the new lake polygon.

When I diff your PR DBF with my branch DBF it looks like some of the names have changed. So I'll need to rectify that separately on merging your PR. The hazards of binary files :\

**Comment by matkoniecz** [comment]
> When I diff your PR DBF with my branch DBF it looks like some of the names have changed.

Have I also modified them? I was pretty sure that I have not did this.

> The hazards of binary files :\

Is it maybe feasible to switch to geojson or something else that is diffable and generate shapefiles from that? QGIS could break for example encoding of Arabic names I would be unable to spot that.

**Comment by matkoniecz** [comment]
>  Can you also add the 10m_rivers_lake_centerlines theme and make sure you the lines are consistent, and update your screenshot, please? The rivers should still come in and out of the lakes on a node... and the lake centerlines need to be 100% inside the new lake polygon.

screen06

Tiny changes were made, I snapped them. Also fixed connection between Śniardwy and Tałty at https://www.openstreetmap.org/#map=17/53.80239/21.57146 (extremely minor but it was annoying me, in previous PR version there was a tiny disconnect).

Luckily it still should not conflict with my other PR as there are no major rivers here :)

**Comment by nvkelso** [comment]
@matkoniecz can you verify the `10m_physical/ne_10m_rivers_europe.shx` file did not change? They usually do when changing the DBF and SHP components, but I don't see it included in this PR.

**Comment by nvkelso** [comment]
> Is it maybe feasible to switch to geojson or something else that is diffable and generate shapefiles from that? QGIS could break for example encoding of Arabic names I would be unable to spot that.

Ideally Natural Earth switches management of the source files to GeoJSON for "truth" and generates the SHP during final packaging ... but there are a handful of files that exceed the default file size limits for Github. So either they need to be trimmed down in size (unknown work) or we ask for an exception from Github.

**Comment by matkoniecz** [comment]
> @matkoniecz can you verify the 10m_physical/ne_10m_rivers_europe.shx file did not change? They usually do when changing the DBF and SHP components, but I don't see it included in this PR.

I have no unpushed changed, I opened this data in QGIS and it appears fine

screen02

> So either they need to be trimmed down in size (unknown work) or we ask for an exception from Github.

Or maybe split in parts?

**Comment by nvkelso** [comment]
>> So either they need to be trimmed down in size (unknown work) or we ask for an exception from Github.
> Or maybe split in parts?

That's intriguing, thanks for the tip!

**Comment by nvkelso** [comment]
LGTM, thank you!

**Review by nvkelso — APPROVED** [review]

**Pull request merged**
