### PR TITLE
v5 prequel

### PR DESCRIPTION
**Pull request by nvkelso**
Generally:

- v4.1.0 geojsons
- add more name localizations
- add POV worldview for admin-0, admin-1 & etc
- few minor bug fixes along the way (this PR got too long)

Specifically addresses the following issues:

#20 add disputes between Slovenia and Croatia adm0 disputed_area
#24 Add disputed area Braziliera I. between Brazil and Uruguay adm0 disputed_area
#79 Update population and GDP estimates for admin-0 to circa 2019 housekeeping
#195 Incorrect UN features adm0
#221 Campobello Island and Deer Island adm0
#255 Bir Tawil and Halaib unclaimed territories not present adm0 disputed_area
#268 Shouldn't Norway's ISO_N3 be 578? adm0
#284 ISO_A2 for France is -99 instead of FR adm0
#301 Support points of view (worldview) for admin0 disputed areas areas adm0 disputed_area
#313 Incorrect coding of Kazakhstan in sovereignty dataset adm0
~~#315 Separate metropolitan from overseas territories (France, Norway...) adm0~~
#331 The Taiwan is a part of China. Please fix the data . Appreciate you ! adm0 disputed_area
#355 Missing Virginia part of Delmarva (Eastern Shore) in several datasets adm1
#390 map of Ukraine mistake adm0
#391 Bug with Crimea. adm0 (dupe #390)
#401 Improper map of Ukraine adm0 (dupe #390)
#410 Swaziland has changed there country name to - Eswatini adm0
#442 Territory of Azerbaijan adm0 disputed_area
#481 countries10 pop_est year 2017 for Papua New Guinea incorrect adm0 (dupe #79)
#569 fix country names inside populated places
#399 Rerun all the Wikidata name translations (eg Wrong name_en value for Puebla, Mexico)
#451 Add Persian language support
#484 Document QGIS localization options (names, boundaries, admin-0 polys)
#541 add POV to maritime boundary indicators and redo China 9-dash line
#533 full support for Chinese simplified and traditional localized names
#235 gps_code is icao_code
#511 add missing Tuvalu to admin-0 themes
#479 Add more 50m data for states/province (like 10m theme)

### CODE REVIEW

**Comment by nvkelso** [comment]
New preview ZIP (partial files):

- 
[v5.0.0-pre8-boundaries-pov-chinese.zip](https://github.com/nvkelso/natural-earth-vector/files/6845759/v5.0.0-pre8-boundaries-pov-chinese.zip)

**Comment by nvkelso** [comment]
Last few commits address:

#569 fix country names inside populated places
#399 Rerun all the Wikidata name translations (eg Wrong name_en value for Puebla, Mexico)
#451 Add Persian language support

**Comment by nvkelso** [comment]
The populated places POV columns in [v5 beta 5 release](https://github.com/tilezen/vector-datasource/issues/1840#issuecomment-497583012) went missing along the way and need to be restored. This mostly affects places in Taiwan (extant data in beta 5) but also a handful of other localities that are country or regional capitals of disputed areas (like Kosovo, Crimea, and more that need to be edited still).

In populated places theme I also noticed the GEONAMESID column went missing when #5 was fixed in error, so also adding that back.

**Comment by nvkelso** [comment]
New preview files:

- [v5.0.0-pre9-boundaries-pov-chinese-pops.zip](https://github.com/nvkelso/natural-earth-vector/files/7035254/v5.0.0-pre9-boundaries-pov-chinese-pops.zip)

Namely the following themes are updated, mostly minor POV data edits (except):

- **ne_10m_populated_places** (added missing `fclass_*` columns and few data files)
- **ne_10m_admin_0_boundary_lines_disputed_areas**
- **ne_50m_admin_0_boundary_lines_land**
- **ne_10m_admin_0_disputed_areas_scale_rank_minor_islands**
- **ne_10m_admin_0_disputed_areas**
- **ne_50m_admin_1_states_provinces_lines** (added Brazil, South Africa, India, China, Russia admin lines)
- **ne_50m_admin_0_boundary_lines_disputed_areas**

**Comment by nvkelso** [comment]
New preview:

- http://naturalearth.s3.amazonaws.com/beta/v5.0.0-pre9-boundaries-pov-chinese-pops-hydro-admin.zip

Adds:

- ne_110m_lakes
- ne_10m_admin_0_countries
- ne_10m_admin_0_map_units
- ne_10m_admin_1_states_provinces
- ne_10m_lakes
- ne_50m_lakes
- ne_10m_playas
- ne_50m_playas

Which all have localized names needed for Tilezen to build.

**Comment by nvkelso** [comment]
The POV could always use more tender loving care, and will get more QA, but time to merge this very big and old PR.

**Comment by rshopa** [comment]
As @nvkelso has closed every single issue regarding his recognition of Crimean occupation, I shall copy my recent post here. Still waiting the response from the GitHub support on this violation:
@nvkelso Closing multiple 

> @nvkelso
> 
> > The default boundaries and country boundary remain defacto and don't change from version 4, here with English labels.
> 
> I **strongly disagree** and **shall report** wherever possible this issue, as the developers ostensibly violate the International Law. UN statement, all Western countries, most of the rest of the world clearly stated that they support the integrity of Ukraine and recognise its borders as of the beginning of 2014. Crimean Peninsula is not even disputed under Ukrainian law, it is "temporarily occupied".
> 
> One more, I stress that the so-called "de-facto" status, even if introduced, is highly unpractical since it's difficult to achieve consistency. For instance, it does not depict other territories, occupied and controlled by Russia - Transnistria, occupied Donbass, DE-FACTO even Belarus (the first picture). I suspect the same is about Tskhinvali and Abkhazia (not painted in "russian"). Moreover, the ongoing conflicts (such as between Azerbaijan and Armenia) might change borderlines on a daily basis, rendering such map obscured.
> 
> The only logical reason this so-called "de-facto" version might exist is that the developers did not act in good faitn and their goal was ONLY to justify the Crimean occupation. Therefore, **I consider you and the Natural Earth team as those who support terrorist acts, invasion and mass-murder made by Russian Federation and question the Ukrainian sovereignty**, by introducing this so-called "de-facto" formula. I also encourage the rest of the people who had left the post here to make similar statements.
> 
> The "russian" version should not exist in the first place as it justifies the war crimes. I considered it the same as if, e.g. you added the ISIS or Taliban version of the map.

**Pull request merged**
