### PR TITLE
Add supplimental Australian lakes, rivers and update NA hydro

### LINKED ISSUE #474: Update North American supplemental hydro
Per Tom Patterson's recent work.

### LINKED ISSUE #475: Add Australia supplemental hydro at 10m
Per Tom Patterson's new contribution.

### PR DESCRIPTION
**Pull request by nvkelso**
Fixes  #474 and #475; and #590 for new physical region wikidataids and names.

Will need additional work to normalize the data to match NE v5 conventions, and over to @ImreSamu to add wikidata_id and localized names.

### CODE REVIEW

**Comment by ImreSamu** [comment]
my wikidata suggestions -->  https://github.com/nvkelso/natural-earth-vector/issues/475#issuecomment-917433599

**Comment by nvkelso** [comment]
I added Tom's North America hydro changes for https://github.com/nvkelso/natural-earth-vector/issues/474 in https://github.com/nvkelso/natural-earth-vector/pull/580/commits/bb58c23e714d681ae76cdf35e3e92a9cf1af50d4 including remaking / verifying all the random issues the earlier work in v5 had changed.

But the global rivers and lakes still need some processing mostly for the Russia river changes, but a general pass over everything.

The Australia rivers now have wikidataid and name translations in https://github.com/nvkelso/natural-earth-vector/pull/580/commits/ff2941429dbed67b324fc8a78ce4440f7c36e57a, but we're missing 5 languages.

**Comment by nvkelso** [comment]
The North America rivers are mostly ready to go now, modulo the `tp_guid` column which is used for QA, adding ne_id for the new features, and name translations (if there are new wikidataid to add).

**Comment by nvkelso** [comment]
The new North America rivers now have `ne_id` per https://github.com/nvkelso/natural-earth-vector/commit/0a03f04f942af8bb43c64f323939c959736abc71.

**Comment by ImreSamu** [comment]
> The new North America rivers now have ne_id per 

Ok .. I will re-run my code ... on the river_north_america.

I hope the  "lake_north_america" is still valid  ( https://github.com/nvkelso/natural-earth-vector/issues/591 )

**Comment by nvkelso** [comment]
>  Derive the not-scale-rank 10m rivers from the scale-rank updates

Via https://github.com/nvkelso/natural-earth-vector/pull/580/commits/2683ebef5c4cb819838a7524ee41e2ee2fd057ca and https://github.com/nvkelso/natural-earth-vector/pull/580/commits/4a2b69ddd564f4b917cebf7e8e9137799f09eb0c.

**Comment by nvkelso** [comment]
This is probably ready to merge, but let's have a look with fresh set of eyes.

**Comment by nvkelso** [comment]
The last commits add additional localized names for:

- ne_10m_admin_1_states_provinces.shp
- ne_10m_geography_marine_polys.shp
- ne_10m_geography_regions_elevation_points.shp
- ne_10m_geography_regions_points.shp
- ne_10m_geography_regions_polys.shp
- ne_10m_lakes.shp
- ne_10m_playas.shp
- ne_10m_rivers_lake_centerlines.shp

And related 10m, 50m, and 110m themes.

**Comment by nvkelso** [comment]
I believe this is ready to merge, but will look at it with fresh eyes.

**Pull request merged**
