### PR TITLE
[WIP] Assigned ISO-3166-2 codes where possible.

### PR DESCRIPTION
**Pull request by migurski**
Used fuzzy string matching and external data, with this script: https://gist.github.com/migurski/4a5821699e1ed519a604

The only affected column should be `iso_3166_2`, but it looks like character encodings for Asian `name_local` values may have been corrupted during `ogr2ogr` moves. What is the correct encoding for these?

### CODE REVIEW

**Comment by nvkelso** [comment]
The character encoding for that file should be UTF8 as of version 3, but you might be operating on version 2 which was still Windows1252.

I've been trying to push version 3 of to Github for a while now, but they changed their 100 MB file max size policy and there are a few ZIPs causing issues. Removed those but it's still cranky.

**Comment by nvkelso** [comment]
The Asian names were separately corrupted when the master ArcGIS GeoDB (in UTF8) was exported to SHP format in Windows-1252 in the version 2 series. It appears you are using a file from the 2 series and not the 3 series. 

The better fix would be to apply this change on top of the version 3 SHP file which is now master and in UTF8 code page for the DBF. I believe fixing ne_10m_admin_1_label_points_details.dbf and then (my) rebuilding the project would propagate the change to the related 10m and 50m scaleset files. 

Version 3 also includes WOE IDs and FIPS codes for almost all these same features. It can be downloaded directly from naturalearthdata.com at http://www.naturalearthdata.com/downloads/10m-cultural-vectors/10m-admin-1-states-provinces/.

**Comment by migurski** [comment]
That does sound like a much better fix. I’ll follow up with you offline to see what we can do about these big files.

**Comment by migurski** [comment]
Replacing with https://github.com/nvkelso/natural-earth-vector/pull/128.

**Pull request closed without merging**
