### PR TITLE
In .geojson files, fix Norway's values for ISO_A2 ('NO') and ISO_A3 ('NOR')

### PR DESCRIPTION
**Pull request by lmanul**

### CODE REVIEW

**Comment by lmanul** [comment]
For what it's worth, the failure seems to come from the tooling rather than from an issue with the change?

**Comment by nvkelso** [comment]
The GeoJSON are just an export of the original shapefile (with those values stored in the dbf). The original should be modified and then the GeoJSON exported fresh.

But... the codes you want are in a different admin-0 theme / natural earth has a different setup than you’re used to in how it maps to ISO. It’s a common enough complaint I’ll propose an alternate solution? Have you checked iso_a3_eh?

**Comment by lmanul** [comment]
Oh sorry, I guess it's a "user error" then :-) I thought it was a bug, but I guess Norway is a special case. Sorry for the noise!

**Comment by nvkelso** [comment]
The data should be easy to use, so everything can be improved :)

**Pull request closed without merging**
