### PR TITLE
Aral Sea and North American Hydro Edits for 6 Issues: #337, #472, #426, #41, #308, #425

### PR DESCRIPTION
**Pull request by MrGawsome**
This PR includes work I did in my previous PR, #502. To do this, I created a new branch based upon my previous branch that contains the edits of PR #502 just to play it safe and to avoid potential issues. For this new PR though, here are the issues and edits I did:

### **Aral Sea Edits:**
Rather than making a new PR, GitHub updated this PR to include my Aral Sea edits since the edits were done on the same branch. For these edits, I cleaned up the Aral Sea for issue #337 by splitting the sea into 5 geometries following the above sources and Bing Aerial Imagery. I edited the attributes and geometries of these features, as shown below:

A: name = Aralkum Desert 
ne_id = 1729982847
featurecla = Playa 
name_alt = South Aral Sea 
wikidataid = Q276776
scalerank = 1
name_abb = `` (NULL) 
This was done on the ne_10m_playas shapefile.

B: name = South Aral Sea 
I used the original ne_id of the Aral Sea for this feature.
featurecla = Lake  
name_alt = Southern Aral Sea|Large Aral Sea|Big Aral Sea 
wikidataid = Q276776
label = South Aral Sea
name_abb = `` (NULL) 

C: name = North Aral Sea 
ne_id = 1729982865
featurecla = Lake  
name_alt = Northern Aral Sea|Small Aral Sea
wikidataid = Q3358037
label = North Aral Sea
name_abb = `` (NULL) 

For B and C, I left the original scalerank, min_zoom, and min_label as discussed but originally changed them following other similarly sized features. Let me know if you want me to change these fields.

D: name = Barsakelmes Lake 
ne_id = 1729983019
featurecla = Lake  
name_alt = Tushchybas|Tsche-Bass Bay|Shche-bas Bay
wikidataid = Q28750379
label = Barsakelmes Lake
name_abb = `` (NULL) 
scalerank = 6
min_zoom = 5.0
min_label = 6.5
wdid_score = 5

E: name = `` (NULL) 
ne_id = 1729983021
featurecla = Lake  
wikidataid and all name/label fields = `` (NULL) 
scalerank = 9
min_zoom = 7.0
min_label = 8.0
wdid_score = 5

This above work was done for the ne_10m_lakes shapefile. For the ne_50_lakes and ne_50m_playas shapefiles, I did the same work except I removed E and simplified the geometries of all of these lakes and playas. For the ne_110m_lakes shapefile, I removed all features as discussed. Originally I included B and C so if we want these features back, I can re-add them.

### **North American Edits:**

For #472, I added the below edits for ne_id = 1159113251 in the ne_110m_lakes shapefile:
name = Great Salt Lake 
name_abb = Great Salt L. 
label = Great Salt Lake 
wikidata = Q178741

For #426, I added the below edits for ne_id = 1159109029 in the ne_10m_lakes shapefile:
name = Napaktulik
name_alt = Takijuq|Takiyuak
wikidataid = Q1546823

For #41, I changed the min_label of **Salish Sea** to `6.0` for ne_id = 1159120759 in the ne_10m_geography_marine_polys shapefile.

For #308, I edited ne_id=1159114515 in the ne_10m_rivers_lake_centerlines shapefile by adding the missing lake centerlines for the Alsek River. I did this by using pinakographos’ centerlines and snapping the river polylines to the end points of the lake centerlines. I used all of the attributes of the “Correction” shapefile the issue reported attached for the lake centerlines since it seemed like it followed the main river’s attributes and were similar to other lake centerline attributes, except I also added the following attributes:
label=Alsek River  
wikidataid=Q1781851
dissolve=233Lake Centerline (let me know if this should be null instead)
ne_id=1729949123 (I generated this id using https://www.brooklynintegers.com/create/)

I also added the following attributes to the river polyline (ne_id=1159114515):
name=Alsek River
label=Alsek River  
wikidataid=Q1781851

Here are some sources to confirm this river's name and wikidata:
USGS map: https://www.usgs.gov/centers/asc/science/alsek-river?qt-science_center_objects=0#qt-science_center_objects
Alaska.org: https://www.alaska.org/detail/alsek-river
Wikidata: https://www.wikidata.org/wiki/Q1781851

For #425, I created a new lake named Whitefish Lake in the ne_10m_lakes shapefile and created a new small river connecting Whitefish Lake with Lynx Lake in the ne_10m_rivers_north_america shapefile (since that is where the lake centerlines were). To do this, I split Lynx lake (ne_id=1159108899), created a gap between the split features, and gave the northern feature the following attributes:
name=Whitefish Lake
name_abb=Whitefish L.
min_zoom=6.0
min_label=7.0
wikidataid=Q22610852
ne_id=1729949125 (which I generated from https://www.brooklynintegers.com/create/)
I also checked the rest of the attributes and they seemed fine.

I then slightly modified the geometries of Whitefish Lake and Lynx Lake only near the gap between the lakes following imagery without being too detailed. 

After this, I split the lake centerline (ne_id=1159145759) for Lynx Lake twice and then merged the lake centerlines for Lynx Lake and Whitefish Lake so they were one feature. A river between the lakes was formed as a result of this. I snapped this river and the lake centerlines with each other and with the lake edges. I then left all of the attributes for the river between the lakes but added the following attributes:
featurecla=River
ne_id=1729949155 (also generated from https://www.brooklynintegers.com/create/)
I left dissolve=21320Lake Centerline just in case it was wanted as a reference. If needed, I can change this to 21320River or even leave as null.

Lastly, I checked to see that all rivers and lake centerlines were connected with each other and lakes in this area, including in the ne_10m_rivers_lake_centerlines and ne_10m_lakes_north_america shapefiles. Everything seems fine here, so that is good.

### CODE REVIEW

**Comment by MrGawsome** [comment]
@nvkelso I added the Aral Sea edits to this PR instead of creating a new PR since I did the edits on the same branch as this PR and it seems like you can only create PR's from new branches if other PR's are open on a branch.

**Comment by nvkelso** [comment]
@MrGawsome Sweat! I'll have a look at all the changes in this PR :)

**Comment by nvkelso** [comment]
The original edits from https://github.com/nvkelso/natural-earth-vector/pull/502 to verify are:

For this PR, I completed edits for 5 issues: #342, #341, #375, #236, and #319. 

For #342, I removed ne features 1159116595 and 1159125751 from the ne_10m_lakes shapefile and changed the lake centerline 1159118279 in the ne_10m_rivers_lake_centerlines shapefile to featurecla “River.” I made sure its attributes were in line with the adjacent river Kabalebo. I left the “dissolve” field as “374Lake Centerline” since it seems we didn’t need to change this field and it may be good to keep it as is for reference.

For #341, I copied the geometry and attributes of Lop Nur (ne_id 1159114133) from the ne_10m_lakes shapefile and added them to the ne_10m_lakes_historic shapefile. I then changed the featurecla to “Historic Lake,” changed the label to “Historic Lop Nur,” and added to the date field “early 1970s.” I then removed the lake from the ne_10m_lakes and ne_50m_lakes shapefiles.

For #375, I extended 3 rivers in the ne_10m_rivers_lake_centerlines shapefile to the ne_10m_coastline following the general shape of Bing Aerial imagery:
Huang River (ne_id 1159128895) 
Luan River (ne_id 1159128523) 
Nakdon River (ne_id 1159127153) 

For #236, I merged the 2 Mediterranean Sea features (ne_id = 1159115321 and 1159116285) and Ross Sea features (ne_id = 1159115615 and 1159115549) for all scales (10m, 50m, and 110m) in the geography_marine_polys shapefiles. For all scales, I kept the attributes of ne_id 1159115321, including this id, for the merged Mediterranean Sea feature and ne_id 1159115615, including this id, for the merged Ross sea feature.

For #319, I edited 2 different features. 
For the first, I edited ne_id = 1159104649 in the ne_10m_geography_regions_polys shapefile. I added Wikidata “Q252609” and changed the name and name_alt fields to “New Swabia” and “Neuschwabenland” respectively. 
The second edit I did was editing a Russian border lake (ne_id = 1159113451) in both the ne_10m_lakes and ne_50m_lakes shapefiles. I changed the name to “Lake Pskov,” name_abbr to “L. Pskov,” name_alt to “Pihkva järv|Pskovskoe Ozero,” and label to “Pskov.”

**Review by nvkelso — COMMENTED** [review]
@MrGawsome Oops, your changes in 10m_physical/ne_10m_geography_regions_polys.dbf conflict with changes in https://github.com/nvkelso/natural-earth-vector/commit/e91173d321243add0a27bc9c8d537acfd00c5cb0#diff-8176d52624268de3a5cf6082553b57a33a69184ce935b1841bce3f5e42db4f3d for https://github.com/nvkelso/natural-earth-vector/pull/505 and prevent a clean PR merge. Please make sure to rebase from `master` and manually apply those edits again.

**Comment by nvkelso** [comment]
In `ne_10m_rivers_lake_centerlines.dbf` there appears to be an spurious feature? Between **ne_id** = `1159129685` and `1729949123` in the DBF. Might be junk introduced during digitization in QGIS?

```
303Drau	7	River	Drau	Drava	303		6	Drau	7	Drau	Q171009	درافا		Drau	Drava	Drava	Drave	Ντράβα		Dráva		Drava	ドラーヴァ川	드라바 강	Drau	Drawa	Rio Drava	Драва	Drava	Drava		5	1159129685
	0				0		0		0																							0	0
233Lake Centerline	6	Lake Centerline	Alsek River		233		5		6	Alsek River	Q1781851																					0	1729949123
```

**Comment by nvkelso** [comment]
Note for #472 (Great Salt Lake in 110m) and maybe others, the basic name and Wikidata ID are fixed... but it still has the old name localizations. So I'll need to re-run the update names script before release – which is normal and not a blocker for this PR being merged.

**Comment by nvkelso** [comment]
For Aral Sea changes... 

1. Should the eastern spur of the **Amu Darya** continue up to the new playa shown in yellow-orange?
2. The rivers (Amu and Syr Dayra) leading into new South and North Aral Sea lakes need to snap to the polygon boundaries, please. They both overshoot right now.

image

**Comment by nvkelso** [comment]
For the 50m Aral Sea changes:

1. Please thicken the narrow bits and reduce spikeyness of North Aral Sea. You can add another vertex or two to help reduce the spikey.

image

**Comment by nvkelso** [comment]
For Lop Nur:

The playa shape should continue under the historic lake (should include that as part of the playa) polygon. Now they are two non-overlapping polygons.

image

**Comment by nvkelso** [comment]
For #342, and ne_10m_lakes shapefile and with 1159118279 you need to change the **dissolve** field as “374River” since it is used to generate label dissolves and some joins, please.

**Comment by nvkelso** [comment]
> For #425, I created a new lake named Whitefish Lake in the ne_10m_lakes shapefile and created a new small river connecting Whitefish Lake with Lynx Lake in the ne_10m_rivers_north_america shapefile (since that is where the lake centerlines were).

Generally good, but one quibble that the **dissolve** field should instead say `21320River` for the new feature **ne_id** = `1729949155`.

**Review by nvkelso — CHANGES_REQUESTED** [review]
Please see multiple comments, including to resolve the file conflict (and retype those edits).

**Comment by MrGawsome** [comment]
> Actually, for this #342 and related issues in #375 and #425 (more?) you should instead be making your edits in the **ne_10m_rivers_lake_centerlines_scale_rank** file, as the _ne_10m_rivers_lake_centerlines_ is a derived file for labeling. So you'll need to remake some of these edits (possibly make use of exploding features and then replacing parts of them into the scale_rank theme?). I'm very sorry :\

Hi Nathaniel,

It is no problem, I believe I understand what I need to do. I will simply copy over any geometry and attribute changes I did on the ne_10m_rivers_lake_centerlines file to the ne_10m_rivers_lake_centerlines_scale_rank file. This includes changes to the following fields: name, label, min_zoom, dissolve, featurecla, ne_id, wikidata, scalerank & min_label (for new features), and possibly name_alt (not sure if I edited this last field off the top of my head).  I will not merge together parts of a river in the scale_rank file since these have different strokeweig numbers as discussed yesterday in our meeting. Let me know if this isn't correct.

This leads to one question I have though. For the features that I created from scratch (such as the Volga-Don Canal or small river segments in my Russian water system edits), should I create a strokeweig number for these features (based upon nearby strokeweigs?)? Also, would you like me to populate other null fields, such as dissolve, scalerank, and wdid_score? I believe I added a scalerank to these new features but haven't touched the other fields above.

Here is a screenshot of the Volga-Don Canal I added in my local ne_10m_rivers_lake_centerlines file but haven't made in the ne_10m_rivers_lake_centerlines_scale_rank file yet:

Volga-Don Canal

Thanks for the help!

**Comment by nvkelso** [comment]
Yes your general understanding sounds right. You can do that either manually or with join and field calculation.

> This leads to one question I have though. For the features that I created from scratch (such as the Volga-Don Canal or small river segments in my Russian water system edits), should I create a strokeweig number for these features (based upon nearby strokeweigs?)? Also, would you like me to populate other null fields, such as dissolve, scalerank, and wdid_score? I believe I added a scalerank to these new features but haven't touched the other fields above.

Yes, there are a minimum set of fields that must be filed in including **rivernum**, **dissolve**, **scalerank**, **min_zoom**, and **strokeweig**.

The first 2 are so the scale rank river pieces can be union'd into the label rivers. The later 3 are so we know the relative zoom and graphic importance of the features for actually drawing them on the map.

For your example if you fill in the **min_zoom** and **dissolve** then you should be set? Choose the next largest **rivernum** value manually by sorting in the table to find the current largest value and +1. Then the **dissolve** is a concat between the min_zoom and the **rivernum**.

**Comment by MrGawsome** [comment]
Sounds good, thanks for the clarification! I'll let you know if I have any other questions.

**Pull request merged**
