### PR TITLE
Makefile geojson updates

### PR DESCRIPTION
**Pull request by mfogel**
This PR contains updates to the options to passed to `ogr2ogr` to improve the generated geojson. Since the geojson checked into the repo was last updated (re: #229) gdal 2 was released and geojson was standardized with an RFC. 

 * generate RFC7946-complaint geojson, rather than the old 2008 version
 * add bounding boxes to geojson
 * remove some options gdal 2 doesn't support when writing geojson output

With these changes, during generation of the geojson files for the oceans `ogr2ogr` complains about a self-intersection of the input geometry, but the output file looks fine all the same. This can be replicated by running `make zips/10m_physical/ne_10m_ocean.zip`

Tangentially related: the `geojson` directory is all gziped. I know over in `whosonfirst` the geojson isn't being gzipped. Any reason in particular to gzip it here but not there?

Thanks for all your work on this, and WOF as well. Cheers.

### CODE REVIEW

**Comment by nvkelso** [comment]
This generally looks right, I just need to run it once to verify the output is as expected. Thank you!

> Tangentially related: the geojson directory is all gziped. I know over in whosonfirst the geojson isn't being gzipped. Any reason in particular to gzip it here but not there?

It may have to do with GIT LFS unhappiness. That support was beta during the v3 Natural Earth sprint and GitHub has changed their policy / file size limits around it a few times. I vaguely remember a couple of the files were too big? I'll revisit during final review of your PR.

> Thanks for all your work on this, and WOF as well. Cheers.

You're welcome 😄

**Comment by mfogel** [comment]
> I vaguely remember a couple of the files were too big?

You're probably thinking of `ne_10m_roads_north_america.geojson` and `ne_10m_urban_areas_landscan.geojson`. They're currently listed in the [.gitignore](https://github.com/nvkelso/natural-earth-vector/blob/dbe544151f2f27c02f358e81ccbe8026c2298fe4/.gitignore#L6) and currently generate at 128M and 70M uncompressed, 33M and 8M with `gzip --best`.

It looks like github now [allows up to 100MB files](https://help.github.com/articles/working-with-large-files/#conditions-for-large-files) without use of git-lfs. In WOF-data I see records [up to 79M](https://whosonfirst.mapzen.com/spelunker/id/85632793/) stored without any special handing.

**Comment by nvkelso** [comment]
It looks like GDAL 2.2 is required, not just any 2.x series.

- http://www.gdal.org/drv_geojson.html

I have GDAL 2.1.2, released 2016/10/24 installed on my computer. I suppose I should upgrade ;)

But I'm on a Mac and usually install from:

- http://www.kyngchaos.com

But he only offers GDAL 2.1.3. It sounds like 2.2 is in the works per 2017/05/14 note. But until that time I'm leary of building GDAL from source. I've done that before and I end up in a poor upgrade path hell.

For the v4 series we can either remove the  `-lco RFC7946=YES` bits or not merge the PR at all. Then we can revisit this in a later v4.x release.

Digging into this farther.... RFC7946 does 1 things we care about, and 1 thing we don't care about:

- We're already in WGS84 "projection" so no worries there
- We're probably getting the 17 units of decimal precision instead of 6. But OGR 1.9 and up supports another way to set this: `COORDINATE_PRECISION=6`.

@mfogel Can you update the PR to use `COORDINATE_PRECISION=6` instead of the `-lco RFC7946=YES`, please?

**Comment by nvkelso** [comment]
As to the `.gz` of the geojson, I've dug around and I'm not sure where that happens. The gz were last mod in b8f2bac424876e217c9c074bf067ee02c764b033, but I don't see a clue there.

I'm happy to try to go with the basic geojson files instead of the gz bits. That part is already done, the gz just need to be removed and the geojson added back (they get made automatically when any theme is zipped, so they stay up-to-date).

**Comment by mfogel** [comment]
Sounds good, PR is now updated to use `COORDINATE_PRECISION=6`

**Comment by mfogel** [comment]
I noticed the geojson files produced by `ogr2ogr` contain a fair amount of extra whitespace. Pipping them thru [jq -c](https://stedolan.github.io/jq/) to compact them shrinks them by ~20%. If you're open to adding `jq` to your toolchain I can adapt the makefile to include that compaction step.

**Comment by nvkelso** [comment]
@mfogel Sure. I've installed **jq** via Homebrew, please update the PR to include that compaction functionality.

Who's On First uses a slightly different (custom) compaction schema where each property element is on a single line, and the geometry is all on one line which is similar but much more useful for diffs. It's possible Natural Earth will switch to that in the medium term future, but for now the *jq* compaction is appreciated 😄

**Comment by nvkelso** [comment]
I tested on a few features and this is working for me. Thanks!

**Pull request merged**
