### PR TITLE
Update ISO codes for France and Norway 

### PR DESCRIPTION
**Pull request by Joseph51D**
Fix incorrect ISO codes for France and Norway

Fixes for issues: #252 #284 #252

### CODE REVIEW

**Comment by hugolpz** [comment]
@ajmass @mfogel @nvkelso : core contributors of the project are no longer actually active. Could you integrate more contributors as owner so we keep improving the repos ? People having contributed PR being perfect candidates.

**Comment by J4bbi** [comment]
@nvkelso, thanks for a brilliant and useful project

is there any chance you could look at this PR or if you find that you don't have time for this, involve more people as maintainers?

I am using Natural Earth for my own non-commecial purpose and ran into this at a late development stage in a sense it is a comfort that the problem was with source data and not code but it's a simple thing to fix, right?

Happy new year

**Comment by nvkelso** [comment]
I had a look at the PR and it modifies the default `ISO_A2` column values for parts of France and Norway in a way that is _not consistent_ with Natural Earth's practice of being strict on the ISO code mappings, so cannot be merged as-is. The "strict" mapping are already available in the other **map unit** admin detail themes (not **country**). 

Because Natural Earth has a more fidelity than ISO, and tracks countries that ISO doesn't, Natural Earth maintains it's own set of 3-character codes for each admin-0 related feature. The original intent was consumers of Natural Earth would maintain their own data code mappings between their "worldview" and this data. But most people use the ISO 2-char and 3-char shortcuts included in the data properties. 

The `ISO_A3_EH` ("eh" as in _okay but not great_) column addressed the "fuzzy" or "loose" use case (while introducing possible errors in your visualization &/or analysis depending on how your data is setup – you should interview your data). But it looks like you are working with 2-character ISO codes and not 3-character ISO codes. That's a fairly common use case, and I can see adding a new `ISO_A2_EH` column for this. 

The place to do this is in the housekeeping OpenOffice file and then to use the Makefile targets to rebuild the SHP and GeoJSON files. I've been sprinting on v5 and have modified those file extensively in my branch, so I'll include this in my next commit and link it here for you to test.

**Comment by nvkelso** [comment]
> is there any chance you could look at this PR or if you find that you don't have time for this, involve more people as maintainers?

@J4bbi I welcome any help! I mostly tinker with Natural Earth when there's a major issue that needs to be fixed, or when I want to add a new feature (currently working on boundary POV worldviews). Generally Natural Earth is small enough scale it doesn't need a lot of maintenance, but it does creep up over time. I sometimes can work on it during work hours, but often it's during personal time and I also have a family (youngest son just turned 1 year old) so don't have endless time for it.

One tricky thing for collaboration is there are several interlocking files in Natural Earth and it's not always obvious which file needs to be updated in the "src" versus modifying the output SHPs, and the various scale ranks (1:10m, 1:50m, and 1:110m), and the SHP are binary and don't show a good diff in PRs.

In other projects (like Who's On First) I've moved to keeping the raw data as specially formatted GeoJSON instead, which solves the diff problem. I'd like to change NE to that practice, but some of the files in GeoJSON format are at the Github file size limits. 

Regarding the other pieces, I am working with a couple collaborators for v5 – you can see reported issues and a recent PR for populated places updates and we're documenting some of these workflow pieces in a GIST that will then get incorporated into a proper README. Hope the background helps, and again, if you're interested in helping please reach out!

**Comment by nvkelso** [comment]
The following 2 commits (branch not mainline) 

- https://github.com/nvkelso/natural-earth-vector/commit/cd16b951daf68025ab7f515764fdc690cdd1167c
- https://github.com/nvkelso/natural-earth-vector/commit/709ffdf7e55f73a0d81dd1adcb4a1032a38e3730

Add `iso_a2_eh` column, addressing the FR and NO cases (and others):

Screen Shot 2021-01-06 at 09 16 35

Screen Shot 2021-01-06 at 09 16 53

Preview GeoJSON:

- https://github.com/nvkelso/natural-earth-vector/blob/v5-prequel/geojson/ne_10m_admin_0_countries.geojson
- https://github.com/nvkelso/natural-earth-vector/blob/v5-prequel/geojson/ne_50m_admin_0_countries.geojson
- https://github.com/nvkelso/natural-earth-vector/blob/v5-prequel/geojson/ne_110m_admin_0_countries.geojson

Please let me know if that addresses your concerns.

**Comment by nvkelso** [comment]
(I've also done the same with `iso_n3_eh` for #268 in subsequent comm it, same preview file links.)

**Comment by J4bbi** [comment]
thanks for the update @nvkelso, this is great and does indeed help me

I have actually been matching NE with CIA World Factbook data and I mistook their coding for ISO2 (I now realise it's FIPS 10-4)

Nonetheless, it's an improvement obviously.

Your project Who's on First looks awesome.

**Comment by nvkelso** [comment]
Closing in favor of https://github.com/nvkelso/natural-earth-vector/pull/446.

**Pull request closed without merging**
